- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: us-east-2
      instance_type: t2.micro
      ami: ami-cfdafaaa  # Redhat
      keypair: RedHatforchef # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: "AKIAIXACWHIKZIUHTTTQ"
         aws_secret_key: "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"
         group: launch-wizard-5  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: "Demo"
         instance_tags:
            Name: "Demo"
         vpc_subnet_id: "subnet-d59bc0ae"
         assign_public_ip: yes
      register: ec2
#boto required 
